### ISSUE TITLE
Calendar and time pickers don't work when editing a party

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#104]
The pop-up calendar and time pickers don't display when editing a party.  Tested in Firefox & Chrome.  They work fine when creating a new party.

----

![image](https://cloud.githubusercontent.com/assets/172324/24160306/52b7ca6c-0e59-11e7-9f46-65ae0eb39bf9.png)

----

**Comment by ngm** [comment]
@IronRunes confirm that this works locally - could you push to production please?

**Comment by IronRunes** [comment]
pushed
