### ISSUE TITLE
Deleting an event on Fixometer doesn't delete from Wordpress

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/Fixometer#105]
I've created a test event, without adding any device, then I deleted it without problems in the Fixometer. However the event is still published in Wordpress, and the only way to get rid of it is to manually unpublish it from Wordpress. 

The correct behaviour should be: when an event is deleted on the Fixometer, it is also automatically deleted in Wordpress

**Comment by IronRunes** [comment]
REMINDER: use the deletePost in the wrapper class to delete stuff in WP

**Comment by ngm** [comment]
As discussed... in the rare cases where communication link with WP fails after the deletion from the Fixometer, for now we trap the error and let the user know what has occurred.  If it is a host, we ask them to report to an administrator, if it's an admin, we let them know that it needs to be deleted manually.  I'll provide the text for this shortly.

**Comment by ngm** [comment]
@IronRunes just tested and this didn't work.

Steps:
* created an event for Restart HQ
* was created in fixometer and Wordpress
* clicked 'delete' from list of upcoming events
* got a blank page (500 error I guess)
* event was deleted from fixometer, but not from Wordpress
