### ISSUE TITLE
Automatic Password Recovery

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#112]
In the login page, we need to add a "Forgot your password?" option. If users click on that, they enter their email address and receive an email with a temporary password, which they have to reset upon logging in.

**Comment by IronRunes** [comment]
I went a slightly different route about this: enter email, get email with "password reset URL" that expires after 24 hours. :) hope it suits.

**Comment by ngm** [comment]
Some quick notes on what helps testing the email locally:

```
$ gem install mailcatcher
$ mailcatcher
```

```
$ apt install ssmtp
$ vim /etc/ssmtp/ssmtp.conf
```
> mailhub=localhost:1025

```
$ vim /etc/php/7.0/apache2/php.ini
```

> sendmail_path = /usr/sbin/ssmtp -t

```
$ sudo apachectl restart
```

**Comment by ngm** [comment]
Functionality works great.  A couple of UX/design suggestions that I'll work on and put into separate issues.  However I'll mark this as complete, as these issues will be low priority.
