### ISSUE TITLE
Setup/test SMTP on the server

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#113]
In order for the email functionality to work, we will need an SMTP server running on the server.

Wordpress is sending emails, so we should be able to reuse that one.

**Comment by IronRunes** [comment]
@ngm Isn't this done? :)

**Comment by ngm** [comment]
@IronRunes The code all worked fine locally - just leaving it open until tested on the production server.

**Comment by ngm** [comment]
(Oh that reminds me - off topic - but wonder your thoughts on something like PHPMailer or similar, ever used them?    No need for just now (as we have just one email being sent :) ), but if we ended up sending more mails then something that's a bit more testable/mockable than the mail() function might be handy.  Wasn't so keen on having to alter php.ini for mail.)

**Comment by ngm** [comment]
Emails take 5/10 minutes to send, and arrive in my spam folder.  Need to investigate, but for now adding some extra text to let the user know that this might be the case.
