### ISSUE TITLE
Searching/filtering for list of devices

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#117]
We should be able to search/filter by the following criteria:

- category
- group (if possible)
- date range
- model (including if empty)
- brand (including if empty)
- text

To do:
- [ ] wireframe

**Comment by IronRunes** [comment]
hey @ngm I'll assume that the searching filter that we got running in the search page can serve as a mockup for this functionality, right?

**Comment by ngm** [comment]
@IronRunes correct

**Comment by ngm** [comment]
## Small things
* Swap Brand and Model fields in the search bar
* 'Search in the description...' placeholder text -> 'Search in the comment...'

## Bigger things
* Can we get it to keep the search options when we hit Search?
  - reason: common user flow would be to explore data by incrementally filtering, but currently have to repeat search each time
    - e.g. first I think - I want to see Misc categories, so I select Misc, then I hit search 
    - I look at the results for a bit, then I think - I want to to restrict this to Restart HQ - I have to select Misc again, and Restart HQ and Restart the Capital in the categories
    - then I think - actually, only those for this year - I have to select Misc again, then Restart HQ and Restart the Capital, then the dates.
    - etc...

* For Model/Brand/Comment, any easy way to specify 'Is empty?' as the search criteria i.e. bring back results only where that field is empty
  * e.g. a checkbox for that column that says 'Is Empty?', or a string/wildcard character that represents 'is empty'?
  * Reason: we want to improve data quality, and one of the problems is unentered data for Model/Brand
    -  Would be nice to search for e.g. both model and brand empty, and we would see the number of devices in the results count
  * *Workaround*: when we order by a column, the empty results come at the top
