### ISSUE TITLE
dashboard - login page

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#12]
- "welcome to the fixometer" text - (Janet to write)
- login module
- devices restarted (total)
- co2 de-sequestered to date (total)
- kg of waste prevented (total)
- bar chart waste/co2
- total restart parties to date
- total upcoming parties

**Comment by IronRunes** [comment]
Need Janet's text - I think that the bar chart won't work here, space is too small

**Comment by janetgunter** [comment]
Here's a first go:

"Welcome to our community space, where you can share upcoming Restart Parties and track their social and environmental impact. By doing so, we can empower and motivate at a local level, but also build global momentum for a change"

Is this the right length? 

I'm not even sure we want to call it the "Fixometer"

**Comment by IronRunes** [comment]
added text, will be working on the chart

**Comment by IronRunes** [comment]
chart added

**Comment by janetgunter** [comment]
Can we change the CO2 chart to "CO2 emissions prevented" please? thanks

**Comment by janetgunter** [comment]
Could we also change the photo to https://www.flickr.com/photos/96189004@N04/14763131053/in/album-72157645868786976/ instead? Is there a way to credit Heather Agyepong
