### ISSUE TITLE
Add product age field

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#131]
A new field to record the age of a product.

## TODO

- [ ] spec
- [ ] wireframe

## Notes

Data:
* New field in the devices table.  Need to think about format and value, e.g. is it recorded in months.

UX:
* In terms of UX, it could sit underneath the Brand/Model/ - in the same "column"

**Comment by IronRunes** [comment]
add this to:
device list
device modal
party manager

**Comment by ngm** [comment]
We think the best granularity for the datatype for this would be integer, to record age in months.  

* Days is to too fine-grained
* Years is probably too coarse grained, and for the time we want to record months we'd have to do it as a fraction of some kind
* Months can always be rolled up into years if needed in reports or interfaces

@ugomatic would you agree with recording product age in months?

**Comment by ngm** [comment]
Some office discussion here with @ugomatic - no problem with months in the database, but needs a little thought in terms of the interface as to how we ask for it to be recorded - quite likely people will only go in half year increments.

**Comment by ngm** [comment]
Notes from comparison of data sources:

* How should we represent age?
  * As a raw number? 
    * Then, is it in months or years?
  * As a choice from a discrete set of options?
    * E.g. less than 6 months; between 6 months and 2 years; etc 
* What does the age refer to?
  * Age from manufacture?
  * Age from purchase?

**Comment by ngm** [comment]
Further discussion about this - we are currently uncertain as to what is the best format to take with this information.  @ugomatic will be looking further into what information is normally used by for example EU commission reports into product durability.  This will help inform what we record.

As to what age we're recording, both could potentially be useful.  Age since manufacture tells us e.g. how long before a product fails.  Age since purchase could tell us something about consumer behaviour with regards to repair.  In an ideal world we would be able to record both of these, however have to bear in mind the level of information we ask to be collected.

Intuition is that if we have to choose one, then age since manufacture is most important in terms of stories we want to tell.  (Although note that age since manufacture would be the easiest to figure out after the fact - if we have product model number recorded.)  We may understand more on this though in the coming months through discussions around OpenRepair.

The question of raw number vs discrete options is also interesting.  From looking at data sets, once a product is over a year old, people rarely record the number of months.  Also have to bear in mind that it's not always possible to know from model number the exact number of months since manufacture.

Summary - we don't know *exactly* what we want for now, it will be discovered over the coming months.  So we will use freetext for the datatype.  In the interface help text we will encourage the user to input number of years since manufacture.  But given it is free text it provides the option to type whatever they choose.  We will revisit once a reasonable amount of data has been collected and if a clear choice of discrete options or precise datatype becomes available, we will do a bulk convert to that and amend the interface accordingly.

**Comment by ngm** [comment]
Todo - to mock-up where in the device editing forms this field will go.
