### ISSUE TITLE
add "e-waste prevented"  to co2 desequestered bar chart

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#14]

**Comment by tingeber** [comment]
try out putting them together, if scale is weird we can split them in two tabs

**Comment by IronRunes** [comment]
I've done this, but it doesn't seem to be working nicely. numbers are too different to be portrayed like that. I'll see if we can have two barcharts and a button switch.

**Comment by IronRunes** [comment]
done

**Comment by janetgunter** [comment]
There's a bug when I'm logged in as Restart HQ (Restart Party Host) - the text needs to read "CO2 emissions prevented" 
![uploads/93f361e5-fbe2-48d2-b0f4-12209af60229/Screen Shot 2015-09-14 at 09.34.46.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F93f361e5-fbe2-48d2-b0f4-12209af60229%2FScreen+Shot+2015-09-14+at+09.34.46.png)
