### ISSUE TITLE
Issue with 'Join Us' link being pulled out of Description correctly

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#144]
Sometimes the link that is put in the first line of the description is not displayed correctly on the front-end wordpress site.

Think it is if the URL ends up wrapped in a div somehow.

But regardless, probably a better solution here is to have a new field which is 'Website'.  This is easier for the user to understand, and removes the need for parsing the Description on the front-end.

**Comment by IronRunes** [comment]
group edit/create
