### ISSUE TITLE
Formatting issues when copy pasting into Description for events

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#146]
Sometimes users copy paste existing info into the Description field from an existing website.

This can results in bad formatting on the front-end.

e.g. https://therestartproject.org/parties/aylesbury-hp21-7rt/

## Ideas

* Strip HTML tags when pasting into the editor?

**Comment by ngm** [comment]
Works but doesn't seem to strip out font size...

## steps to reproduce

* Take what's in this gist:
https://gist.github.com/ngm/af8b0bf025e3c74faefcb167edf8bd67#file-messy-html

* Copy it into Code View for an event, view it in HTML, save it

* Should then look like this: 

![image](https://user-images.githubusercontent.com/172324/28457190-1371c138-6dfd-11e7-9c03-8e3b0b775229.png)

* Cut the contents of the description box and paste it back in (so now we're recreating a user pasting from web or Word)

* Looks like this:

![image](https://user-images.githubusercontent.com/172324/28457288-6f2f9f22-6dfd-11e7-964d-9efc2333ec8e.png)

* Font size is too large - it still has font-size: 18px in the HTML

* Can strip it out by selecting all the text and clicking the Remove Font Style button

Is there a summernote setting to also remove font-size when pasting in?

**Comment by IronRunes** [comment]
myself to pull updates to summernote & cleaner

**Comment by IronRunes** [comment]
I tried copy/pasting from a word document. It works perfectly. My assumption is that it preserves well formed HTML, for some reason, but it also kind of makes sense.

**Comment by ngm** [comment]
Not necessarily related to this, but there's a bug in summernote-cleaner such that it doesn't correctly strip the style tag if there is an apostrophe in the styling.

e.g.

![image.png](https://images.zenhubusercontent.com/57e24b8995e42b6c5ba93892/a789f64d-1cc3-4fdc-b16f-838b1edda739)

becomes 

![image.png](https://images.zenhubusercontent.com/57e24b8995e42b6c5ba93892/5bf0ce03-5923-49cb-9db6-e3d537f981ab)

(screenshotted the HTML as otherwise github strips it out of my comment...)
    &lt;plucida console'"="">asdf<p></p></plucida>

**Comment by ngm** [comment]
Anyway let's roll with this for now, I changed the options such that it should be keeping a few basic tags, but still stripping out all styling.
