### ISSUE TITLE
Inline help for group editing

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#147]
For each field, the ability for the user to see some help on what's expected to go into that field.

Most likely an 'i' button next to each label, that when you hover over shows you the related help.

**Comment by ngm** [comment]
@IronRunes to implement, myself to provie text.

**Comment by IronRunes** [comment]
myself to prep tooltips in the form, text will come in later

**Comment by IronRunes** [comment]
look for placeholders:
{REPLACE TITLE} and {REPLACE CONTENT}
