### ISSUE TITLE
Host dashboard fixes

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#15]

**Comment by tingeber** [comment]
- you have X upcoming parties - click on X to have the screen scroll to it
- same with X parties need your attention
- move "my profile" link to top right menu, maybe "my profile" drop down w logout, edit profile links? put mini pic next to "my profile"
- next to group profile NEW MODULE: group main stats
- upcoming restart parties: add link to "view all upcoming parties", that links to therestartproject.org upcoming parties
- Latest restart parties: change to "All $GroupName Parties" put inside scrollable div, max height 5.3 parties

**Comment by janetgunter** [comment]
Can we change to "All $GroupName Parties" instead of "All $GroupName Restart Parties"? Thanks!

**Comment by IronRunes** [comment]
done, will be pushed later today

**Comment by janetgunter** [comment]
A couple of questions re. the data: 
- the hours volunteered figure seems extraordinarily high for ours. Can we check what is going on there?
- speaking of which the CO2e prevention figures also strike me as high - just confirming that the displacement coefficient 0.5 is being used there? 
- I think we need to clarify that the no. of participants INCLUDES Restarters - ours does.

Thanks!

**Comment by janetgunter** [comment]
One last thing: when logged in as Admin, the aggregate totals of waste prevented and CO2e prevented appear to include our "cheating" (add on from 2013) but when logged in as Restart HQ host, the aggregate totals are lower, not including 2013

**Comment by IronRunes** [comment]
- hours volunteered = ((number of volunteers * 3)  + 9 (host hours) ) * number of parties hosted; 
if no "volunteer number" is available, we assume 4 volunteers for 3 h (12 h). 
- displacement is in being used, and is equal to 0.5
- yes, it's tricky to include that quota in only one host profile.

**Comment by janetgunter** [comment]
Ah, ok hehe you mean we're actually counting all of MY time? ;) cool of course.

All the rest is cool thanks

**Comment by janetgunter** [comment]
in the visualisation of achievements, it's weird that the first time you see the logos of categories, much smaller, they have no name below them (hard to see them really), while the second time, you get to see them bigger and with text underneath them: maybe this can be fixed by putting Category Details first, and Devices Restarted per Category underneath?
