### ISSUE TITLE
Inline help for party management

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#151]
@IronRunes to provide infrastructure, myself to provide text.

**Comment by ngm** [comment]
![image](https://user-images.githubusercontent.com/172324/28128266-124cd93c-6727-11e7-9f9e-663049da64d0.png)

**Comment by ngm** [comment]
Need to bear in mind that this text needs to be translatable in the next release.

**Comment by IronRunes** [comment]
myself to prep tooltips in the form, text will come in later

**Comment by IronRunes** [comment]
added to the table headers for clarity and to avoid useless proliferation 
look for placeholders:
{REPLACE TITLE} and {REPLACE CONTENT}
