### ISSUE TITLE
Need to force formatting on text on event page

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#164]
Currently when users Copy/Paste text into the free text box on the event page, all the formatting is maintained and we have to go back in and clean everything up. Can we force formatting to our own, while maintaining embedded links? 
![screen shot 2017-07-03 at 10 18 46](https://user-images.githubusercontent.com/4210588/27786439-1161f9d0-5fd9-11e7-9ee3-05911bedd49d.png)

**Comment by ngm** [comment]
We're currently looking into this in #146 - we've got a solution that strips out the existing formatting when  content is pasted in, which means when it loads on the Wordpress page it will have our formatting.  I'm not sure what will happen with embedded links - will be testing it soon, although @IronRunes might be able to comment.

**Comment by ngm** [comment]
This is now implemented in #146.

Currently configured to keep basic tags such as links, but to remove all custom formatting and use ours.

It might need some tweaking over time if we find some weird edge cases, so we'll keep an eye on it.
