### ISSUE TITLE
Engine Room old logo on all WP Fixometer pages

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#167]
Could we please change this out for the new logo (used inside the Fixometer app itself)? Ta!

**Comment by ngm** [comment]
Notes to self: 

* e.g. therestartproject.org/impact
* The old file is https://therestartproject.org/wp-content/uploads/2015/10/engineroom.png   
* New logo is at: https://www.theengineroom.org/wp-content/themes/theengineroom/img/footer-logo.png
* Might be able to simply replace this file in Wordpress media library, need to new image doesn't get skewed though.

**Comment by ngm** [comment]
It's now updated in both the Fixometer back-end and on the front-end (for /impact, and group and event pages.)
