### ISSUE TITLE
Documentation for new users

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#17]
- Main features explained, and rationale for the platform
- What gets published to the main site - this is the best way of announcing an event in advance (although it's not obligatory)

**Comment by janetgunter** [comment]
Start this without screen grabs https://docs.google.com/document/d/1HgfJAML03U3yO1GoEkVdsV6tkVgqS-UPZt0brDMMPvs/edit

**Comment by tingeber** [comment]
Blocked by #55

**Comment by janetgunter** [comment]
I'm adding this as a page to our website - I'll share the link here 

(@ironrunes to create a link to this page in the header of the Fixometer - I will share text for that as well)

**Comment by janetgunter** [comment]
http://therestartproject.org/?page_id=7065&preview=true - I think we need a little help formatting (numbering each item?), and perhaps anchor-links at the top?

**Comment by IronRunes** [comment]
I've added a link to the User docs in the header of the App for hosts.

**Comment by janetgunter** [comment]
Thanks, looks good on App but I'm still wondering how to add numbering and anchor-links as a kind of table of contents? (If it's tedious tweaking, perhaps you can just do one and I'll finish the rest?) Sorry I'm not a WP pro...
