### ISSUE TITLE
Connection is not secure warning 

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#171]
If you navigate to http:// version of site, in Firefox, receiving a warning 'Content is not secure' on the login screen.

Pretty sure it only started happening recently.

![image](https://user-images.githubusercontent.com/172324/28328644-1934bb9a-6bdf-11e7-863a-6544a5ed0d82.png)

Doesn't seem to appear once logged in.

If go to  https:// directly, no problem.

**Comment by ngm** [comment]
@IronRunes one thing that I changed related to this during last update was the HTTP_PROTOCOL setting, to https - related you think?

Reason I did this was the links that are placed in the password emails are built from this, so wanted them to be https links.

**Comment by IronRunes** [comment]
not really - this is a server issue. It means that Apache is not redirecting http requests to https requests. We should look into the apache conf files for that specific vhost.

**Comment by ngm** [comment]
Added:

    RewriteCond %{HTTPS} off
    RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [NE,L,R=301]

to .htaccess on the server.
