### ISSUE TITLE
CREATE ALGORITHM generate rights issue and won't create

### ISSUE THREAD

**Issue by vguenichon** [TheRestartProject/Fixometer#173]
This is it. I'm just at the beginning... with a database user who has all privileges granted.
But this won't create and generate an error of rights.
Is it possible that, even with all granted privileges, a user can't create algorithm ?

**Comment by ngm** [comment]
You'll probably need to change the DEFINER of the algorithm to the user that has rights on the DB.

e.g. on line 163 of `InitialiseDB.sql` change it from `fixometer_root` to whatever your user is called.

**Comment by vguenichon** [comment]
Of course I did this... error is still there.
Will check with my hoster.

**Comment by ngm** [comment]
Yes if you're on a shared host it's possible they've restricted particular rights.  
Can you paste the error you're getting here?

**Comment by vguenichon** [comment]
`#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation`
But it doesn't matter... as I didn't understand at all how to install, what folder is called through Apache, what's the relation with Wordpress, etc.

**Comment by ngm** [comment]
There is a basic wiki page [here](https://github.com/TheRestartProject/Fixometer/wiki/Installation-Guidelines) on installation.  It is quite bare bones at the moment, and is geared towards installation on a local development machine, however please do feel free to ask questions on any specific problems you have, this will help us to expand it.

**Comment by vguenichon** [comment]
Yes I followed this guide and... I didn't understand the following things:

- what's the relation with Wordpress ? Is it only to have a front for the app ?
- knowing this, why declaring a new website ?
- what is the "web" folder exposed

I think I have many question as I'm not developer but have the skills to install an app.
But I'm aware to give you as many feedbacks as you want.

**Comment by ngm** [comment]
* Yes Wordpress is to have a public-facing front-end.  In our case, information entered into the Fixometer backend is pushed through to https://therestartproject.org . In future we'll be decoupling this better from Wordpress, so it could push to various applications if required.  At present though you don't have to setup a Wordpress site - nothing will fail it you don't have one.
* What do you mean by "declaring a new website"?
* What do you mean by ""web" folder""?

Also, just out of interest - what are you trying to achieve with your installation?  If you're setting up a community repair group, it's possible we could add your group to our hosting of the Fixometer.

**Comment by vguenichon** [comment]
I'm volunteer in a small repair organization in France. And we have the willing to develop a shared web platform of repair and make it open-source. We just discover your initiative and maybe we're going to fork it in order to improve it with our needs. We are more interested in the OpenDataStandard which is, by our thoughts, the main part and the more difficult to achieve.
So I tried to install it to discover what you've done and if it suits to what we imagine.

**Comment by ngm** [comment]
Great!  Happy to help wherever we can.  And we're also keen to collaborate with others, so if it suits your purposes but there are features missing, feel free to put in an issue and we might be able to work on it with you.

**Comment by vguenichon** [comment]
Thanks a lot. Together will win ;-)

**Comment by ngm** [comment]
In case you haven't seen these pages, here is some more information on what the application looks like and does:

* https://therestartproject.org/fixometer/
* https://therestartproject.org/welcome-to-our-community-space/
* https://therestartproject.org/faq/
