### ISSUE TITLE
Google's reverse geocoding is confusingly inaccurate

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#181]
Testing here: https://developers.google.com/maps/documentation/geocoding/intro

If I geocode 'stamford hill library', it correctly picks out the coords and the address of the library:

![image](https://user-images.githubusercontent.com/172324/35240497-8aa2e59e-ffab-11e7-872c-f5521df40333.png)

If I click exactly on that spot as a test of the reverse geocoding, it reverse geocodes to 102 stamford hill.

![image](https://user-images.githubusercontent.com/172324/35240414-4cfb36a6-ffab-11e7-8606-cb82f0953859.png)

Same thing happens if you geocode/reverse geocode with their JS API (test [here](https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse)).  As such, the same inaccuracy occurs with our geocoding/reverse geocoding in the Fixometer, which means we get the wrong address displayed on the front-end.

**Comment by ngm** [comment]
I suggest that now we have a field specifically for the address, we should just display that as the address on the public promotional page of the party, no need to reverse geocode (except perhaps for the pushpin on the map - which for the cases where it's slightly off, at least the written address will be correct.)  This way should also be less confusing for a user creating a party, as what they enter and what they see displayed will always match.

Only proviso here is that we should only do this for parties created (or last modified) after the date that v3.0 was released (22nd Jan 2018), as for events before that the location field will be the name of the party.

**Comment by NikhitaPaturu** [comment]
* The location variable($location) is not present in the front-end, in order to fetch and use it in the back-end code(single-party.php and gmaps.js).

**Comment by ngm** [comment]
The issue is that we do not currently send both the party venue and the party address to Wordpress from the Fixometer.  We need to make the new party venue field available to Wordpress as well.

**Comment by ngm** [comment]
This is in place, though currently without the date check.

This means that for now, old events (those before 22nd Jan) will show the contents of the location field - which for those events will be the short venue name.  Not a big problem as this is for past events.  We will come back to this and resolve this.
