### ISSUE TITLE
Geocode function during group creation not working

### ISSUE THREAD

**Issue by jstricklin-coutinho** [TheRestartProject/Fixometer#184]

**Comment by ngm** [comment]
geocoder.js is being shared between group creation and party creation pages, and on group creation page there is no 'venue' element (newly added), so the JS is failing.

Either separate files for each page, or put a check in for existence of venue field.

**Comment by ngm** [comment]
Fixed: remove attempted use of venue field in geocoding altogether. 
Obviously wasn't being used for groups geocoding, and for parties, given the way in which the 'venue' field is used (as a generic party name, or a general area e.g. Tooting), it doesn't provide any benefit by having it included in the geocoding.  The exact venue name should be included along with the rest of the address in the 'Location' field when geocoding.
