### ISSUE TITLE
Unable to paste copied text into event description fields

### ISSUE THREAD

**Issue by jstricklin-coutinho** [TheRestartProject/Fixometer#188]
Tested in Firefox, Chrome, and Vivaldi on Windows 10.  Able to type into description box and to see options to paste and to paste as plain text when right clicking in field, but no text appears after attempting these functions.

**Comment by ngm** [comment]
What is the text @jstricklin-coutinho - i.e. where is it being copied from?
It could be something specific to the HTML that is being copied.
For example, I can paste some text into the Description - e.g. your comment above should copy and paste fine into the Description box, could you confirm?

**Comment by ngm** [comment]
Confirmed with @jstricklin-coutinho - copy/pasting not working into the Florence event.

**Comment by jstricklin-coutinho** [comment]
![chrome error](https://user-images.githubusercontent.com/25587794/35973327-e827c10c-0ccc-11e8-919c-deca1608e398.JPG)

Here's the error text in Chrome Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by ngm** [comment]
Could be a Chrome version thing - not receiving this error on Chrome 63.0.3239.132.
But @jstricklin-coutinho also reported error on Firefox.

**Comment by ngm** [comment]
@NikhitaPaturu - could you confirm if you see this behaviour?  I think you also reported it previously if I remember correctly.

**Comment by NikhitaPaturu** [comment]
@ngm - Yes, I reported this problem too and it still exists with the same error report as above posted by jstricklin-coutinho.

I have tested this on 
- chrome version 65.0.3325.181.
- Firefox version -59.0.1.

<h5>But this works fine in Internet Explorer version 11.0.9600.18952</h5>

**Comment by ngm** [comment]
We discovered that this is was an issue with the version of summernote that we are on, which has subsequently been fixed.  Updating summernote and summernote-cleaner has resolved the issue.
