### ISSUE TITLE
Host Restart Party list - date fix 

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#19]
Instead of picture/logo, big date + venue big 

On start of year, empty row with big chunky year number (like FB)

**Comment by janetgunter** [comment]
There's a small issue with the "add information" version of events in the list - image of my screen on Chrome attached

![uploads/05e94ba2-19d8-44f5-8a0c-7ca2b6088bf3/Screen Shot 2015-07-23 at 10.18.15.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F05e94ba2-19d8-44f5-8a0c-7ca2b6088bf3%2FScreen+Shot+2015-07-23+at+10.18.15.png)

**Comment by IronRunes** [comment]
please hard refresh (ctrl + f5)

**Comment by janetgunter** [comment]
It still looks like this, with the last icon dropped into a second line - not ideal

**Comment by janetgunter** [comment]
There is some kind of bug where a party that is happening in one hour's time appears as already having occurred? 
![uploads/45fd1eb1-8333-4536-80b4-527846ab9f7b/Screen Shot 2015-08-11 at 16.47.40.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F45fd1eb1-8333-4536-80b4-527846ab9f7b%2FScreen+Shot+2015-08-11+at+16.47.40.png)

**Comment by IronRunes** [comment]
fixed
