### ISSUE TITLE
Create/Edit Group Profile

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#20]

**Comment by tingeber** [comment]
- add image (avatar, icon, logo)
- description: possibility to add links, h1, h2
- remove frequency
- remove area
- Location: change to "Location: where do you keep your fixing tools and supplies?"

**Comment by IronRunes** [comment]
Note to self: need to check integration of images

**Comment by janetgunter** [comment]
When I try to edit or improve some group's information logged in as Admin, I get "Fatal error: Call to undefined function HieuLe\WordpressXmlrpcClient\xmlrpc_encode_request() in /var/www/Fixometer/lib/vendor/wordpress-xml-rpc/WordpressClient.php on line 848"

**Comment by IronRunes** [comment]
Yes, as anticipated, working on Wordpress/Fixometer today might cause
some issues.
Should be fixed in a few minutes.

Il 30/07/2015 15:26, Janet ha scritto:

**Comment by janetgunter** [comment]
Tried to update our avatar and got this 
![uploads/be176d37-8a1f-42ae-8d53-223bf3c29114/Screen Shot 2015-08-18 at 11.46.33.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe176d37-8a1f-42ae-8d53-223bf3c29114%2FScreen+Shot+2015-08-18+at+11.46.33.png)

**Comment by janetgunter** [comment]
Then went back to main page and got this - can we can an auto-resize function there, and on the User profiles? 
![uploads/9e1a0c7a-5c7b-4025-846c-53ba4d13f541/Screen Shot 2015-08-18 at 11.48.36.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9e1a0c7a-5c7b-4025-846c-53ba4d13f541%2FScreen+Shot+2015-08-18+at+11.48.36.png)

**Comment by IronRunes** [comment]
resize is there already, removed zoom/cropping calculations

**Comment by tingeber** [comment]
@janetgunter please close if done

**Comment by janetgunter** [comment]
Everything else works but my user and group avatar are still cropped strangely, not sized to the circle

**Comment by IronRunes** [comment]
@janetgunter yup, you'll need to reupload those in order to have them resized and cropped with no zoom

**Comment by janetgunter** [comment]
Ok, good so it worked for my personal avatar but there are a couple of lines added? 
![uploads/67330ba2-d952-437c-acc9-e5f2c42866e3/Screen Shot 2015-10-02 at 08.55.43.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F67330ba2-d952-437c-acc9-e5f2c42866e3%2FScreen+Shot+2015-10-02+at+08.55.43.png)

And with the group avatar when I try to upload a new .jpg I get this 
![uploads/92a482d4-d75e-4ef8-b842-4ebdfc9db5cd/Screen Shot 2015-10-02 at 08.55.15.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F92a482d4-d75e-4ef8-b842-4ebdfc9db5cd%2FScreen+Shot+2015-10-02+at+08.55.15.png)
