### ISSUE TITLE
New Party

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#21]

**Comment by tingeber** [comment]
- add "public info" widget
- date, start, end on same line
- if simple, populate end time automatically to 3 hours after start time
- description: add links
- remove participants
- remove volunteers

**Comment by tingeber** [comment]
- ADD "add new party info from Meetup" line on top of New Party, it autopopulates the whole thing
- users add the meetup event link - that link gets stored in the database

**Comment by tingeber** [comment]
Separated meetup integration to new card

**Comment by janetgunter** [comment]
Friends, I notice that I cannot change or improve the location of the party afterwards. Is this impossible? because people might mistakes or do like I did and forget to geolocate the venue

**Comment by janetgunter** [comment]
Calendar button isn't working for me

**Comment by IronRunes** [comment]
it is possible for admins, using the party/edit/{id} url.

**Comment by janetgunter** [comment]
I think I will need a button or new "feature" to edit parties, as lovely as "party/edit/{id}" is ;-)

**Comment by IronRunes** [comment]
Sure will, in the Admin Page. that was just for quick reference in the
meantime.

Il 28/07/2015 12:53, Janet ha scritto:

**Comment by janetgunter** [comment]
Thanks!

**Comment by janetgunter** [comment]
So I've noticed something in using the tool: after a party, "Edit Party" is taken to mean add/edit devices. It does not allow the free text about the event to be changed, or location to be "improved" or photos to be uploaded. 

I notice this is only possible from the /Parties list, which is only visible to admins - Hosts should be able to edit their events from /Parties - correct?

**Comment by janetgunter** [comment]
From @ugomatic: 
- uploading images: 
1) the cursor in the form seems to indicate you can type/edit a file name, when you click you can't, as your only option is to browse - it's a bit confusing
2) when you press "upload" for one/more pictures, it saves the event and sends you back to the homepage instead than just uploading the picture

**Comment by tingeber** [comment]
@IronRunes 
- implement "edit party details" button for past parties as well, for all restart hosts
- remove text bar from "add image", only leave "browse" button
- when you upload the image, user should stay on the "edit party" page

disregard other tasks in this ticket.

**Comment by IronRunes** [comment]
left only the "browse" button, no upload buttons, image gets uploaded when form is submitted
