### ISSUE TITLE
Prevent duplicate form submission on device management page

### ISSUE THREAD

**Issue by NikhitaPaturu** [TheRestartProject/Fixometer#228]
Page: /party/manage

Issue: Save button should be disabled when it is clicked (or triggered via keyboard input), to prevent duplicate form submission.

**Comment by ngm** [comment]
We should probably also adopt PRG pattern.

**Comment by ngm** [comment]
We are going to change this such that it disables the button on form submission, rather than button click.

**Comment by ngm** [comment]
Continued in #262.
