### ISSUE TITLE
Add-edit devices

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#23]

**Comment by tingeber** [comment]
- show party image on top somewhere
- category drop down: add "none of the above", when selected, add below it "estimated weight" free text, in kg
- "Add new device" to be shown in table, left aligned
- add button "SAVE AND EXIT" below table
- [HASSLE CHECK] - passive save each time user clicks on "add device" - possible validation hassles
- stick table headers to top of page when scrolling out of viewport
- spare parts -> checkbox
- Restarter: only for ADMIN; make it a multiple select

**Comment by janetgunter** [comment]
Having trouble entering multiple devices into the system c.f. Grafton Pub Camden - it only appears to save the first device. I'm not going to proceed until it appears to be working...

**Comment by IronRunes** [comment]
bug fixed - working on the rest of the task :)

**Comment by IronRunes** [comment]
Task is pretty much done - won't be able to implement passive save now, and photo adding needs to wait. 
Also we should move restarter selection to task #25 (Admin Main)

**Comment by janetgunter** [comment]
From @ugomatic: Brand/Model: maybe we could have something prewritten in the field, ie. "if you know it"

**Comment by IronRunes** [comment]
- button saves the current party & devices but does not return you to the dashboard
- added indication on the column title
- this is pretty much semantics. "Spare parts" can be either "spare parts USED" or "spare parts NEEDED". When we discussed this, we opted for it meaning "spare parts USED". 
- Should this be available for everyone or only admins?

**Comment by ugomatic** [comment]
- I can't test the save feature: it's currently broken
- ok for column title
- I guess if people select "repairable", then it will mean a spare part is needed, if fixed that a spare part was used
- delete entries should be available to everyone, not only admins

**Comment by IronRunes** [comment]
1. Fixed the annoying issue
2. great
3. Ok, so it's a matter of UX/User guide
4. Will do 

closing this issue and creating a new feature req

**Comment by janetgunter** [comment]
Error after trying to enter data. Context: I opened the party, entered three devices, pressed save and exit. The first two devices were logged properly. Then I tried to change the third (incorrect) and save and exit, and: 
![uploads/2ae0608f-916a-4daa-8935-a24a9ede726f/Screen Shot 2015-08-18 at 12.00.21.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2ae0608f-916a-4daa-8935-a24a9ede726f%2FScreen+Shot+2015-08-18+at+12.00.21.png)

**Comment by janetgunter** [comment]
Now I'm not getting an error message, but data I enter is not being saved, I'm just returned to the main page.

**Comment by janetgunter** [comment]
It's looking good, but there are only a couple more issues - the date of events is getting squeezed out 
![uploads/ff25dc09-6508-4a7b-b9bd-ce4b49b85ad8/Screen Shot 2015-08-25 at 15.43.30.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fff25dc09-6508-4a7b-b9bd-ce4b49b85ad8%2FScreen+Shot+2015-08-25+at+15.43.30.png)

**Comment by IronRunes** [comment]
fixed squished date
