### ISSUE TITLE
Admin main

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#25]
- same as host main, showing all upcoming and latest. it's basically "FULL EVERYTHING"
- Welcome text on top also shows number of guesstimates(!!!).
- global main stats widget on top
ADMIN CONSOLE
- open group page - dropdown (rich, with pic and name) - when opened
- add/edit user
-  add/edit groups
- restart parties: add live filters 1) pink 2) guesstimates
- build querying system for group achievements(!!!!)

**Comment by IronRunes** [comment]
Working on this but somewhat stumped. 
- Need insight on ADMIN CONSOLE (bullet point 3)
- Querying system for group achievements, can't recall what that was about specifically

**Comment by tingeber** [comment]
removing querying system form this ticket, @IronRunes opens new task

**Comment by janetgunter** [comment]
I'm liking it, good work Alan, but I can't seem to use the "Groups" drop down, which I imagine is meant to trigger a "View As" link? It gives me "Forbidden" screen.

**Comment by janetgunter** [comment]
Also, it's strange, I'm seeing "Restart Kilburn" Parties on the firehose of parties (we'll have to change the syntax here?) and not able to see future Parties that Alex from Kilburn says she has created. 
![uploads/a9f4480f-6696-4bc3-8f2f-c01e75090f5d/Screen Shot 2015-07-30 at 13.56.19.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa9f4480f-6696-4bc3-8f2f-c01e75090f5d%2FScreen+Shot+2015-07-30+at+13.56.19.png)

**Comment by IronRunes** [comment]
Yup, I got that weird "Restart Kilburn" text too, looking into it -
There are no future parties in the DB, moreover no parties except the
parties of Restart HQ.

Il 30/07/2015 15:00, Janet ha scritto:

**Comment by IronRunes** [comment]
fixed, added switch for parties -> in review
