### ISSUE TITLE
PUBLIC - single event page

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#26]

**Comment by tingeber** [comment]
##Main info
- event pages as custom WP posts
- pull data from party info in fixometer
- page needs comments

##PAGE VERSION ONE: pre-party
- Title
- hosted by
- date
- time start, time end
- location
- rich text
- button "sign up on Meetup" (if event generated on meetup)

##PAGE VERSION TWO: post-party
- Title
- hosted by
- date
- location
- stats widget (pax co2 rep fix eol)
- dataviz block (desequestrated co2, waste in kg etc)
- rich text
- photos

**Comment by janetgunter** [comment]
These pages are causing bugs in my use of categories.
For example http://therestartproject.org/restarters redirects to a party page - not sure why.

**Comment by IronRunes** [comment]
quick fixed from wp permalink settings

Il 03/08/2015 16:20, Janet ha scritto:

**Comment by tingeber** [comment]
closing ticket, reopen after impact page is ready
