### ISSUE TITLE
Impact page summarising the project and our impact

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#32]

**Comment by janetgunter** [comment]
Working on the text here 

FAQ will need to fit somewhere.

I still have not resolved how to offer the data set for download - I would prefer to force the user to create a guest-login, so we can get an email address... @Ironrunes and @tingeber what is your thinking on this?

**Comment by tingeber** [comment]
the impact page final version will wait for phase 2. closing this ticket for now.

**Comment by janetgunter** [comment]
I consider the text above ready-enough to mockup a page, all that remains are images
