### ISSUE TITLE
Impact page with data embed

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#34]
@IronRunes to create private page on restart website from Dimitri's mockup

**Comment by tingeber** [comment]
blocked by #32

**Comment by DLupo** [comment]
@janetgunter @tingeber @IronRunes 

Hi here are the final visuals for the Impact report 
two versions:
a. Group 
b. Event


![uploads/d8ea4acb-beee-4a40-9c97-b8cddaea8a8d/Impact Event Visual.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd8ea4acb-beee-4a40-9c97-b8cddaea8a8d%2FImpact+Event+Visual.png)

![uploads/9aa63bb8-f42f-4155-b029-661a8927a7e4/Impact Group Visual.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9aa63bb8-f42f-4155-b029-661a8927a7e4%2FImpact+Group+Visual.png)

**Comment by tingeber** [comment]
taking these designs as final, Alan to create two private pages on Wordpress showing these dataviz.

**Comment by tingeber** [comment]
@janetgunter let us know which group and which event we should use for the pages

**Comment by tingeber** [comment]
@DLupo please send production files to @IronRunes

**Comment by janetgunter** [comment]
Here are is the data behind the pictograms and calculations @IronRunes let me know if you have any questions: https://docs.google.com/spreadsheets/d/1Bh5JSJlKzrYB06yJ2uXLZW-VOQkvHT0VXKlgv0G0qZE/edit#gid=1820787426

**Comment by DLupo** [comment]
@IronRunes Here are the symbols used in the impact visuals 

http://ge.tt/6jxC17P2/v/0?c

**Comment by IronRunes** [comment]
this has been implemented on the Fixometer (host page)

**Comment by janetgunter** [comment]
Working text here https://docs.google.com/document/d/1NrffCOBH2NBxupj1eGM8BKwITyt5oMybATDQoJNdQbY/edit

FAQ will need to fit somewhere. https://docs.google.com/document/d/1Fkb7QBtkMqFU6e6uCrpybdEg50yJEAguvqlYc0e2118/edit?usp=sharing

I still have not resolved how to offer the data set for download - I would prefer to force the user to create a guest-login, so we can get an email address... @Ironrunes and @tingeber what is your thinking on this?

**Comment by tingeber** [comment]
@janetgunter we can have a popup when clicking on "download our data" where users are required to enter an email address before downloading, which goes straight to mailchimp, in a separate "DB downloads" list - @IronRunes what do you think?

**Comment by tingeber** [comment]
yes to popup, dummy popup content:

- "That is awesome, do you want to give us your email so we can keep you updated on how the dataset evolves?"
- email input field
- download button: only active once valid email is entered
- checkbox (unchecked) "Subscribe me to your newsletter as well!"
- tiny link "No thanks, just give me the data kthxbai"

**Comment by tingeber** [comment]
blocked by #57

**Comment by janetgunter** [comment]
Is there a way we can link from the iframes to the FAQ? https://therestartproject.org/FAQ
