### ISSUE TITLE
Dataviz

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#37]
List of dataviz components.
1 - @janetgunter sends list of dataviz components, activity and quantity
2 - @tingeber builds wireframes
3 - @IronRunes creates widgets
4 - @DLupo creates final set
5 - @IronRunes updates

**Comment by janetgunter** [comment]
So! This is what we can use to trial the dataviz - I've included Noun project icons for each

Activities 
Driving: 0.12 kg CO2 / km https://thenounproject.com/search/?q=driving&i=49625
Watching TV: 0.024 kg / hour https://thenounproject.com/search/?q=tv&i=33512

Consumables 
Imported case of beer: 21.6 kg https://thenounproject.com/search/?q=beer&i=169448
Weekly Laundry (no tumble dry): 2.1 kg https://thenounproject.com/search/?q=laundry&i=30042
Charcoal BBQ (no food included): 10 kg https://thenounproject.com/search/?q=bbq&i=18610

**Comment by janetgunter** [comment]
@tingeber Dimitri is here with me... how far have you gotten with the mock-up?
