### ISSUE TITLE
Device entry bugs

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#38]
I'm using Chrome.
- When I click Repairable, for some reason the drop-down of three radial buttons does not appear - it only appears after I save and then click directly on "Repairable"
- Also when I am loading each new device, for some reason their backgrounds do not change until I press save. 
- The button says "save and exit" but you remain on the data entry page. I can't find a way to navigate back to the event list without being forced logged-out. (The only way I figured out was to press the Restart logo on the top left. Not super evident.)
- "Add device" only adds one new line, ideally it would add 3? Or more?

**Comment by IronRunes** [comment]
- fixed the "repairable" issue
- wasn't supposed to do that - kind neat effect though, will be working on it - submit a feature request please :)
- you now get redirected to the host dashboard on successful saves
- could be tricky, will investigate - submit a feature request please :)

**Comment by janetgunter** [comment]
Thanks! Oh funny re. "neat effect" and add device, because I swear that it was doing that before. I'm going mad!

**Comment by janetgunter** [comment]
Still having the "repairable" issue

**Comment by IronRunes** [comment]
ctrl + f5. always hard refresh

**Comment by janetgunter** [comment]
logged out, logged in. hard refreshed. got it to work on Safari, now locked out. take your word!
