### ISSUE TITLE
Account creation page

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#39]
People gotta be able to create an account - or should this be added to the log in page?

In the meantime, how are we going to add new users, shall I send emails to Alan?

**Comment by IronRunes** [comment]
i thought that user creation was on admins and hosts / not a public subscription zone.
@tingeber ?
in the meantime, admins can use the /user/create url to create users.

**Comment by janetgunter** [comment]
Ok but I'm not an admin ;) please help?

**Comment by IronRunes** [comment]
Janet got help :) - closing because referenced in Admin Main #25
