### ISSUE TITLE
Admin Console Wishlist

### ISSUE THREAD

**Issue by IronRunes** [TheRestartProject/Fixometer#40]
- Querying system to determine achievements on a filtered basis (filters to be defined @janetgunter  and @tingeber )

**Comment by janetgunter** [comment]
Just to say that now they will be determined by @ugomatic - and this is really urgent for before the end of the year, because we are having trouble filtering/finding old events, and working with new users on this

**Comment by ngm** [comment]
@ugomatic @IronRunes Could we clarify what this is please, and whether this is still part of phase 2?

**Comment by ngm** [comment]
See #88 and #109 .
