### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#41]
Here is the first feedback:
- "I can't figure out where to enter data" (is there a way to improve "new party" button?)
- "Why does my avatar change all of the time?" (can we shut off the "random avatar" widget)
- "How can I go back without having to log-in again?" (navigation is crucial, this has frustrated me too)
- "Why is my other team member not visible?" (where should this go?)

I'll be adding more here as it comes in.

**Comment by janetgunter** [comment]
General feedback from @ugomatic: 
- navigation: we need to have a way for people to know where they are

**Comment by IronRunes** [comment]
fixed the swinging avatar
