### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#43]
- create "back to dashboard" button whenever user is in second-level pages (like edit party)
- if logged-in user tries to access login page, redirect user to their dashboard

**Comment by IronRunes** [comment]
1. Back to dashboard implemented in User Avatar dropdown
2. User login page prevented if logged in already, redirects to dashboard

--coming with commit

**Comment by tingeber** [comment]
also add "back to dashboard" button next to "edit party" title when on "edit" pages (add/edit party, add device info, etc)
