### ISSUE TITLE
dashboard visual tweaks (was "visual critique")

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#44]
dimitri to compile critique on a gdoc for sharing with @IronRunes and @tingeber and @janetgunter

**Comment by DLupo** [comment]
I just shared a folder with a quick feedback / redesign attempt. It is meant initially as a discussion of feasibility, we can later decide about priorities and I can specify sizes, spacing as needed. 

https://drive.google.com/open?id=0B1QuVxAV-xKtfkVRSk1jN0Nvd0oxMWNkY1pLNHZjdTFUMWRuZVlQX2Nhd0Q5eDRQMVZGOEU

**Comment by tingeber** [comment]
beautiful @DLupo

**Comment by IronRunes** [comment]
implemented changes to party list

**Comment by DLupo** [comment]
Thanks Tin, nice implementation @IronRunes

**Comment by tingeber** [comment]
@IronRunes to implement changes under "group achievements", but skip the "impact" session (the big TV, cases of beer etc)

**Comment by tingeber** [comment]
mini fixes:

- give more headspace to the three main sections (upcoming parties, all parties, achievements)
- add line to "achievements"  as the other two main sections
- when no data for upcoming parties, leave more space between this section and the following, and write "There are no upcoming parties. <Add a new party>."
- all parties list, make the container visible by adding 1px grey borders bottom and top (no left or right)

**Comment by janetgunter** [comment]
When I'm logged in as admin, the date for upcoming events bug still exists 
![uploads/7fc77892-19d9-4658-a97c-8d3dd0669e82/Screen Shot 2015-10-04 at 15.28.24.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7fc77892-19d9-4658-a97c-8d3dd0669e82%2FScreen+Shot+2015-10-04+at+15.28.24.png)

**Comment by janetgunter** [comment]
@ironrunes, when you get a chance, can we change "Welcome to the Fixometer, [user]" to simply "Welcome, [user]" - thanks
