### ISSUE TITLE
Footer logos and text

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#46]
Need the WRAP logo, credits, FAQ, tech support.

**Comment by janetgunter** [comment]
Text: This tool was developed by The Restart Project with support from WRAP's Innovation in Waste Prevention Fund, in collaboration with The Engine Room and Circular Ecology. For technical support, please email janet@therestartproject.org

[Do we need some kind of versioning? Reference to the launch date?]

**Comment by janetgunter** [comment]
Here are the logos 
![uploads/1f4f024d-23e5-4c6f-9217-e8349a15ffe2/Circular_ecology_logo_strap_AW_outlined_72dpi-01.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1f4f024d-23e5-4c6f-9217-e8349a15ffe2%2FCircular_ecology_logo_strap_AW_outlined_72dpi-01.png)

![uploads/2bfc1269-7d59-4b26-9225-55369d30958c/eR-logo.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2bfc1269-7d59-4b26-9225-55369d30958c%2FeR-logo.png)

**Comment by janetgunter** [comment]
Thanks Alan, @DLupo could you make some suggestions about how to optimise the footer design? @tingeber your logo kind of disappears here...

**Comment by DLupo** [comment]
Hi Here are two options, 

![uploads/d96ff90d-b3fb-402e-82b6-a3c690e7e5ef/footer 01.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd96ff90d-b3fb-402e-82b6-a3c690e7e5ef%2Ffooter+01.jpg)

![uploads/4a6b712d-5d5a-4bf4-81c6-022a6af87517/footer 02.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4a6b712d-5d5a-4bf4-81c6-022a6af87517%2Ffooter+02.jpg)

**Comment by janetgunter** [comment]
Wow that was fast! Thanks Dimitri! I'm just checking with WRAP to see if they want theirs on there... in which case your second design works best...

**Comment by IronRunes** [comment]
tweaked colors, added wrap logo and sorted by appearance in text

**Comment by tingeber** [comment]
@DLupo to add restart logo to the footer. Erm. Ooops.

**Comment by DLupo** [comment]
Something like this? 



![uploads/4671b00b-1c6c-493b-95ce-7b50c074175e/Footer 3.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4671b00b-1c6c-493b-95ce-7b50c074175e%2FFooter+3.jpg)

**Comment by janetgunter** [comment]
I like that - only problem potentially is the repetition with the engine room's logo? Would it look awful to use the black background "badge" like logo that we have? Would it look better to the left of the Fixometer blurb? @tingeber @ugomatic? thanks!

**Comment by DLupo** [comment]
@janetgunter On the left it would be out of alignment with the rest of the container, it will look like this 


![uploads/72fa0c6e-4b35-439b-8330-b2c94354359d/Footer 2.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F72fa0c6e-4b35-439b-8330-b2c94354359d%2FFooter+2.jpg)

**Comment by janetgunter** [comment]
Ok, I leave it to your discretion.

**Comment by tingeber** [comment]
I vote for second version, with mega logo on left. @IronRunes will implement, and change the restart logo bg color to same blue-green as the "fixometer" text, to make it more distinguishable from eR logo.

**Comment by tingeber** [comment]
No change to logo color @IronRunes - keep the background black
