### ISSUE TITLE
Restart Party name is a geocode

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#49]
Users are required to use a street address or coordinates to geocode a party, and this becomes the name of the event - c.f. this Turin event

We need to talk about the best way to solve this 
![uploads/50dce37d-6662-4e5b-a867-d136d5dc9a2b/Screen Shot 2015-09-14 at 09.54.49.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F50dce37d-6662-4e5b-a867-d136d5dc9a2b%2FScreen+Shot+2015-09-14+at+09.54.49.png)

**Comment by IronRunes** [comment]
This only happens if users voluntarily input coordinates in the "Location" field. Isn't much we can do about that, other than inviting them to only input a street address and clicking on "geocode".

**Comment by IronRunes** [comment]
calling in @janetgunter  and @tingeber for insight

**Comment by janetgunter** [comment]
Yes, but when I put a long and annoying street address (needed to geocode), the name of the event becomes long and annoying street address. I have to go back and change the text in the Geocode line after I've clicked "geocode" to "fix" this

**Comment by IronRunes** [comment]
we might want to talk about this on skype, could be faster. :)
btw, you do not need to put a fully detailed address to get geocoding in MOST cases.

**Comment by IronRunes** [comment]
me and @tingeber discussed this, assigning back to @janetgunter to discuss along with tin again and finalize the solution

**Comment by janetgunter** [comment]
@IronRunes I am available all day tomorrow, if you can ping me on Skype, that would be great.

**Comment by janetgunter** [comment]
I will share text of a user prompt re. addresses (for geocoding) vs. place names (for event titles)

**Comment by janetgunter** [comment]
To share an exact location, please use a street address here and press "geocode". Afterwards, please change this line to a recognisable place name, as this will be used in the event title.

**Comment by IronRunes** [comment]
done

**Comment by tingeber** [comment]
@IronRunes any way of finding a better solution for this? For example:
- add a new text input for "Event Name"
- copy the current content from the current "location" field in it (so that it doesn't come up empty)
- change the "event name" print on the website to show the new "Event Name" database entry
- @janetgunter will manually check all the current event names and fix them

**Comment by IronRunes** [comment]
@tingeber we talked this over quite a bit. adding in database fields isn't a very feasable option at this point. the impact of such an action is incredibly widespread, and work to actually reflect this change would be quite a bit.
