### ISSUE TITLE
Post-party upload of multiple images

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#50]
After the event date has passed, users should be able to upload multiple images from the event.

- new button "upload images" within "edit party"
- multi-file upload

let's talk about this. byez

**Comment by IronRunes** [comment]
image deletion added.

**Comment by janetgunter** [comment]
Thanks the multiple upload appaers to work, although they are not displayed within the Fixometer as yet, so hard to know for certain. 

These will be published to the event page on the site, correct?
