### ISSUE TITLE
Dashboard redesign

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#53]
We are splitting the content of the dashboard into 3 parallel tabs:

The tabs will be placed beneath the top-most data summary line, under the shadowy separator.

Tab 1: Parties
- holds the sections "Upcoming parties" and "All parties"
- no need to have a container for all parties, they can be visualized entirely

Tab 2: Impact
- holds @DLupo impact page design

Tab 3: Details
- holds everything else that's left from the current dashboard page (the entire content of Group Achievements)

**Comment by tingeber** [comment]
on tab styling, @IronRunes implements basic tabs (like in the CO2 emission), @DLupo to then provide visual feedback.

**Comment by janetgunter** [comment]
Is there a reason these changes have not been implemented for the Admin accounts? @IronRunes

I was hoping to show the "aggregate" impact to the donors, so they would see what it will look like.

**Comment by janetgunter** [comment]
Thanks. Just one little bug that I'm experiencing as admin 


![uploads/c57c6abd-9f3f-4343-8a09-d16d7ed38e0e/Screen Shot 2015-10-06 at 19.26.05.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc57c6abd-9f3f-4343-8a09-d16d7ed38e0e%2FScreen+Shot+2015-10-06+at+19.26.05.png)

**Comment by IronRunes** [comment]
Having issues replicating this. What page is it that you're viewing in the snapshot, @janetgunter?

**Comment by janetgunter** [comment]
It's after, logged in as admin, I use "view as" another group, and make some kind of small change. Then I try to use the "view as" menu again, and I get that

**Comment by janetgunter** [comment]
I will share sequence that triggers this

**Comment by IronRunes** [comment]
I'm aware of what triggers the bug. I'll be looking into it ASAP.

**Comment by IronRunes** [comment]
done.
