### ISSUE TITLE
Impact tab in Party view

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#54]
When visualizing a party with list of devices, add two tabs under the party overview bar (date, place, participants etc)

1. Impact - as per Dimitri's design
2. Manage Devices - the current page content

**Comment by tingeber** [comment]
@IronRunes could you decide if this is something we can add to the wrap-up, or if it should go in Phase 2?

**Comment by IronRunes** [comment]
might need to go to phase 2, depends on how large the wrap-up is.

**Comment by janetgunter** [comment]
Ok, my only concern is that then Restart Party Hosts cannot access data on the kg of waste prevented per party.... i suppose as long as this is published to the events pages (once they are published)

**Comment by IronRunes** [comment]
we can work out this need quite faster than building a whole new tab of dataviz. :) let me think it over today.

**Comment by IronRunes** [comment]
I added the value of the ewaste prevented to the "Party Management" page (the one where you add devices). Looking good for me.

**Comment by tingeber** [comment]
@IronRunes 
pls remove decimals from kg of waste - see here http://fixometer.zardtech.com/party/manage/152
