### ISSUE TITLE
Final style tweak session

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#55]
@janetgunter sets up an hour skype coworking between @DLupo and @IronRunes to go over small tweaks and changes to the fixometer layout. This ticket officially closes down the WRAP fixometer backend part.

**Comment by tingeber** [comment]
one thing to add: a link to the facebook group somewhere in the dashboard

**Comment by janetgunter** [comment]
I talked to Dimitri, he's ready to talk to Alan this week... @IronRunes @DLupo can you please contact each other directly to set up?

**Comment by IronRunes** [comment]
Sure, @DLupo I don't think I have your email. I prefer talking on mornings, if that is ok for you, any morning this week can work. Let me know! :D

**Comment by IronRunes** [comment]
All done!

**Comment by tingeber** [comment]
@IronRunes @DLupo can you make a list of changes and tweaks and put it in here?

**Comment by IronRunes** [comment]
we already went through all the changes that @DLupo elaborated and pushed them. 
But, for recording's sake, here they are.
- Smaller login button, more margin on login button
- smaller footer logos 
- Switched SVG of car to cleaner version
- tweaked text in the bubble/tv shadow in the impact view
- Decresed size of Avatar on Impact view, added padding
- Added margin to top of impact view and detail view for consistency with party view
- Styled titles in detail view for consistency
- changed icons for categories wih cleaner version
