### ISSUE TITLE
decide on the web link

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#56]

**Comment by janetgunter** [comment]
therestartproject.org/community

**Comment by tingeber** [comment]
@IronRunes either that or community.therestartproject.org - what works best for you?

**Comment by IronRunes** [comment]
third level domain is way better than subdirectory, so I'd go with community.restartproject.org

**Comment by tingeber** [comment]
@ugomatic could you connect with @IronRunes to organize migration of the fixometer?

**Comment by janetgunter** [comment]
I've just bought the subdomain and set the IP destination correctly.

**Comment by janetgunter** [comment]
For some reason, I just noticed on the "migration" (YAY!) that the paragraph text on the login page is too light, almost illegible. Can we darken a little?
