### ISSUE TITLE
DB download

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#57]

**Comment by tingeber** [comment]
@janetgunter defines fields for download
@IronRunes and @tingeber decide on auto csv creation
@tingeber adds links to DB on impact page

**Comment by tingeber** [comment]
download behaviour for:

link to download data, positioned... somewhere (footer?)
on click, popup.

popup content:
"That is awesome, do you want to give us your email so we can keep you updated on how the dataset evolves?"
email input field
download button: only active once valid email is entered
checkbox (unchecked) "Subscribe me to your newsletter as well!"
tiny link "No thanks, just give me the data kthxbai"

**Comment by janetgunter** [comment]
We'd like to see in the .CSV: 
• Device-specific data (category, comments, repair status, use of spare parts)
• Event name attached to each device
• Date attached to each device
• Group name attached to each device

@ironrunes please let me know if this makes sense :)

**Comment by IronRunes** [comment]
hey @janetgunter makes sense, don0t see any major problem in the data.  
where is the link going to be displayed? application or website?

**Comment by janetgunter** [comment]
Great. The download will happen as Tin details above - on the /impact page

**Comment by IronRunes** [comment]
@tingeber  QUESTIONS ARISE! :question: 
- so are we going to have a distinct list for these emails is Mailchimp, or a I supposed to store them elsewhere/elsewise? 
- we're having the "footer link" in the App and the plain link on the website?

**Comment by tingeber** [comment]
@IronRunes and I talked about functonalities, all clear.

MOAR THINGS:

filename should be "restart-party-data-dd-mm-yy.csv" or similar, as long as there's the data.

@IronRunes please put CC thumbnail on the popup

@janetgunter which CC flavor are we going with?

**Comment by ugomatic** [comment]
@IronRunes @tingeber on the email collection, I suggest:

- let's leave by default checked the "Subscribe me to your newsletter as well!"
- let's give people the option of telling us why they want the data - "Any plans on how you'd like to use the data?"
- save the list of new emails, hopefully with how they want to use the data. This could be a new Mailchimp list or a google docs/similar - any suggestion?
- add to our main Mailchimp the ones who agreed to the newsletter

**Comment by IronRunes** [comment]
please give a look at dynamic export @ http://fixometer.zardtech.com/export/devices

**Comment by IronRunes** [comment]
@ugomatic noted, some of these things aren't feasable ATM. Namely, if we add emails to one list in mailchimp, we probably won't be able to add them to the other one concurrently.  
@ugomatic & @janetgunter I need access credentials to Restart's mailchimp account to get the ball rolling. :) please send over ASAP.

**Comment by IronRunes** [comment]
@tingeber popup would be overly complex to no real benefit of the tool. 
@ugomatic @janetgunter  please checkout the mockup of the form on the following private page:
http://therestartproject.org/download-dataset-test/

**Comment by ugomatic** [comment]
@IronRunes mockup comments:
- leave a bit more spacing between text and form. (but i guess that's just a mockup!)
-  "Subscribe to the Restart Project's monthly newsletter"
- as @tingeber said, make the "Just give me the dataset" bit less prominent (smaller font size?)

**Comment by janetgunter** [comment]
also, can we have the email + subscribe box together, with the other text box below? i think this makes more sense. (I personally don't think we are going to get much out of "how might you use this data" - BTW where do we view/download those submissions?)

**Comment by IronRunes** [comment]
everyhting is going into mailchimp with appropriate custom fields as needed

**Comment by IronRunes** [comment]
Everything has been set up on the private page. 
You have a new list in Mailchimp (which is the list to which people downloading the file will subscribe). 
The list is called "Restart Dataset Downloads".

**Comment by tingeber** [comment]
not working on my comp (chrome OSX)
the form needs styling

**Comment by IronRunes** [comment]
@tingeber  please elaborate?

**Comment by tingeber** [comment]
tested by entering all the data, the download button doesn't work - stays greyed out. the direct link works

**Comment by IronRunes** [comment]
please check if you have any javascript console logs. the theme has quite a few issues with async loades and sometimest just won't catch on jQuery. Also, hard refresh. 
btw, I tested on IE, Chrome and FF - all works smoothly. Could be an Apple-only issue?

**Comment by janetgunter** [comment]
Reporting that I got it to work for me @tingeber @ironrunes - on Chrome, OSX 10.7.5 (I'm a hold out!!)

**Comment by janetgunter** [comment]
I only had one question, open data guru @tingeber, which is whether there should be something about the license here on this page

**Comment by janetgunter** [comment]
Can we please find a way to exclude Y1 Misc "devices" from this download? Should I provide the date from which we would like devices?

**Comment by IronRunes** [comment]
maybe we should exclude all Misc devices? just let me know the year you'd like to exclude otherwise. :)

**Comment by janetgunter** [comment]
I think we should leave misc devices, otherwise the data won't add up... I've included text disclaimer in the comment field about Y1. @tingeber ideas?

**Comment by janetgunter** [comment]
We've had requests for this, as currently there is an empty link in our FAQ

**Comment by IronRunes** [comment]
there's a private page that is ready to be published in WordPress. it should be called "Data Download Test".

**Comment by janetgunter** [comment]
Ok, and have misc devices been pulled from this download? (Also noticing the misc devices from Y1 throwing our stats more generally)
