### ISSUE TITLE
SSL cert

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#59]

**Comment by tingeber** [comment]
@janetgunter @ugomatic we'd really need to SSL-encrypt the fixometer, and at that point we should encrypt the main website as well

**Comment by janetgunter** [comment]
Ok...? what action do we need to take please sir

**Comment by janetgunter** [comment]
Assigning to Ugo, who holds the keys to our website

**Comment by ugomatic** [comment]
@tingeber i've just enquired with the hosting providers, as they offer this as a service. I'll keep you posted. I imagine we'll then need to make some changes to the settings of wordpress, right?

**Comment by ugomatic** [comment]
@tingeber which one should we buy? https://www.vidahost.com/page/ssl-certificates (we might get a discount, not sure how substantial). alternatively, we can buy one elsewhere and just pay for the installation...

**Comment by tingeber** [comment]
I suggest the wildcard cert, that gives you the option to encrypt any number of subdomains.


Gandi has a cheaper wildcard cert: https://www.gandi.net/ssl/standard#wildcard

**Comment by janetgunter** [comment]
Is this done, @ugomatic?

**Comment by ugomatic** [comment]
yes, done - only the wiki still requires some minor tweaking by @tingeber

**Comment by janetgunter** [comment]
Has the SSL cert broken the footer? And we're getting reports the email subscription no longer works either: https://twitter.com/rubbishmaker/status/662597136413040640

**Comment by IronRunes** [comment]
don't htink that the SSL can be cause of that. @tingeber  any ideas?

**Comment by janetgunter** [comment]
Ok weird, I think it could have to do with a "testimonial" plugin that @tingeber  just installed?
