### ISSUE TITLE
Creating a CO2e multiplier for "Misc" devices

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#60]
To solve the problem of our "first year" estimates - the fact that we have no events connected to the estimates (which throws our averages/event calculations)... We are going to add the events, adding the same average kgs of waste prevented per event using the Misc field. 

For this to generate a calculation of CO2 prevented, we need a CO2e multiplier - which will be based on the totals in the database to date: TOTAL CO2e prevented / TOTAL kgs waste prevented. 

(This helps Admins because it will be used in future to estimate CO2e for "miscellaneous" devices, by weight.)

**Comment by IronRunes** [comment]
have TONS of ideas about this - including the fact that averages are bound to fluctuate somehow. maybe the ratio should be a living number. just saying. will take care of this by EOW.

**Comment by janetgunter** [comment]
Ok, well, if that is easy enough to code, but I think we'll have to include ANOTHER question in the FAQs ;)

**Comment by janetgunter** [comment]
@ironrunes Should I enter the Y1 events NOW, or only after you've implemented this? Thanks

**Comment by IronRunes** [comment]
please wait until I'm done? This way we'll transfer the whole thing once it's wrapped up.

**Comment by IronRunes** [comment]
this is ready to be tested on the staging site. please go ahead and let me know. :)

**Comment by janetgunter** [comment]
Ok I tried to log our first ever Restart Party as discussed and got no estimates for impact for the event 
![uploads/a726b1bc-4bb1-41ba-9cc2-d08c3a134c32/Screen Shot 2015-11-10 at 15.49.09.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa726b1bc-4bb1-41ba-9cc2-d08c3a134c32%2FScreen+Shot+2015-11-10+at+15.49.09.png)

**Comment by janetgunter** [comment]
I've finished entering Y1 data on the staging site and it works just fine, thanks!
