### ISSUE TITLE
Changing user type or deleting user as Admin

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#63]
There is no way to delete a user as Admin, so I tried changing a user to a "guest" and got this error 
![uploads/d8ebd54d-6aa5-4b9f-b522-0fddd00884db/Screen Shot 2015-11-23 at 16.00.41.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd8ebd54d-6aa5-4b9f-b522-0fddd00884db%2FScreen+Shot+2015-11-23+at+16.00.41.png)

**Comment by IronRunes** [comment]
same issue as #63. closing this one
