### ISSUE TITLE
Uploading a profile photo

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#64]
I got the following error when I tried to save an uploaded profile photo.  I first changed my password, then went back into Edit Profile to upload  a picture.

James

UPDATE `users` SET `name` = :name, `email` = :email, `new-password` = :new-password, `password-confirm` = :password-confirm WHERE `idusers` = :id (model.class.php, 142)
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'new-password' in 'field list'
)

Fatal error: Call to a member function bindParam() on a non-object in /var/sites/c/community.therestartproject.org/public_html/lib/model.class.php on line 150

**Comment by ugomatic** [comment]
![screenshot 69](https://cloud.githubusercontent.com/assets/4210589/11562087/9be9381c-99c3-11e5-8ae2-0cb1b01690d4.png)

I get the error in the screenshot when trying to update picture. The picture gets updated, despite the error message. But the change only takes place when you go back to the dashboard
