### ISSUE TITLE
Restart Parties have wrong date in admin list view

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#67]
Currently when logged in as Admin, the list of Restart parties all appear to have occurred in 1970. I need to be able to see and sort them by date 
![uploads/6ea22837-ac90-4101-a73a-43dc786826b3/Screen Shot 2015-12-16 at 12.10.24.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6ea22837-ac90-4101-a73a-43dc786826b3%2FScreen+Shot+2015-12-16+at+12.10.24.png)

**Comment by IronRunes** [comment]
Please review on staging site. When checked and accepted, I'll pull amends to the production server.
