### ISSUE TITLE
Deleting a Restart Party 

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#68]
User: "I tried to delete my test event and got this"

Fatal
[ERROR CODE 601]
Could not execute query. Cannot delete or update a parent row: a foreign key constraint fails (`communit81_res`.`events_users`, CONSTRAINT `fkEventsUsersEvent` FOREIGN KEY (`event`) REFERENCES `events` (`idevents`) ON DELETE NO ACTION ON UPDATE NO ACTION) (model.class.php, 183)

**Comment by IronRunes** [comment]
Please review on staging site. When checked and accepted, I'll pull amends to the production server.

**Comment by janetgunter** [comment]
I can't even see how to delete events, I'm logged in as Admin on the test server

**Comment by janetgunter** [comment]
Hoping we can resolve this? Still can't see how to delete events on staging server

**Comment by janetgunter** [comment]
Just noting that I really cannot switch our /events to /parties until this is implemented... @ironrunes. E.g. we have a "test" event from a new user at the top of /parties right now

**Comment by janetgunter** [comment]
We've decided that the work-around is: change the date of the event so it appears in the "Upcoming events" list, from where it can be deleted. THEN ALSO we have to go into WP and delete the page manually.
