### ISSUE TITLE
Proto DB structure

### ISSUE THREAD

**Issue by tingeber** [TheRestartProject/Fixometer#7]

**Comment by IronRunes** [comment]
Please take a look at it right here:
![Proto DB design](https://github.com/TheRestartProject/Fixometer/blob/master/assets/design/EER-Diagram.png)
![eer-diagram](https://cloud.githubusercontent.com/assets/8185000/7027473/e479bfe2-dd4f-11e4-923e-8b78b517b5ed.png)

**Please Note:** This should serve the intention of displaying relationships, more than final fields. I threw some fields in the mix to give it some corpus.
