### ISSUE TITLE
Password set and reset 

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/Fixometer#71]
Currently, Janet creates accounts and assigns passwords. Users are not required to change the password when using the service. If they lose their password, they're stuck and need Janet's intervention to set up a new password. We need this to change in the following way:
1) When Janet creates a new user, she only enters the user's email address - and an email is automatically sent to the new user with a temporary password and the link to the login page 
2) When users log in for the first time, they are redirected to a page requiring them to change their password before they can access anything else
3) In the login page, we need to add a "Forgot your password?" option. If users click on that, they enter their email address and receive an email with a temporary password, which they have to reset upon logging in, as happens in (2)
(I'm sure this can be done in more than one way - we're happy to make it as simple as possible, coding-wise)

**Comment by ngm** [comment]
This was completed in a previous release - must have forgotten to close it at the time.
