### ISSUE TITLE
Saving/editing errors

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#73]
One user: "the fixometer seems to be glitching at the moment - I entered all the data, and when  saved it, it only saved the last one.  I tried again (but only entered a couple before saving) and it happened again, saying error message WP editing."

Another user: "I also tried editing a different event with similar results. I tried saving the data after entering each item and that seems to work, but when I entered three it only saved the last one.  Error message (top of screen): "WP id present (8202)! Editing..." "

**Comment by janetgunter** [comment]
Same thing just happened to me - lost 20 minutes of work :(

"WP id present (8202)! Editing..." "

**Comment by IronRunes** [comment]
I believe this has been somewhat addressed? These issues are gone (might be other ones), correct?
