### ISSUE TITLE
Trouble saving group info and creating new group

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#74]
"Group can not be created. Something went wrong with database"

**Comment by janetgunter** [comment]
Ah ha! It did save. But gives me that error

**Comment by janetgunter** [comment]
I am still getting the same error message, even though it creates the new group. Now I am having trouble with the names and images of new groups. I just added the Milan group and it looks like this. Leicester had trouble changing its image 
![uploads/7e396dc4-a0c3-4ca1-aca7-f790136bff53/Screen Shot 2016-09-14 at 15.13.58.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7e396dc4-a0c3-4ca1-aca7-f790136bff53%2FScreen+Shot+2016-09-14+at+15.13.58.png)

**Comment by IronRunes** [comment]
this could've been caused by a number of local server issues. I went in the fixometer (live), entered Milan editing page and saved without any issue, and updating the title in Wordpress automatically.

**Comment by janetgunter** [comment]
Ok now running into problems changing a group avatar, when I upload a new image, I get no feedback that it is uploaded. I press save and get "string(6) "groups" int(2) 9" at the top of the page

**Comment by janetgunter** [comment]
First I get a page that's an error. Then I go backwards, and try to reupload the image. It actually works, but gives me the error message
![uploads/1b2a4c13-ac01-4cd7-be18-ff669617e40a/Screen Shot 2016-09-23 at 12.44.48.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1b2a4c13-ac01-4cd7-be18-ff669617e40a%2FScreen+Shot+2016-09-23+at+12.44.48.png)

![uploads/5fd75c0e-f7d8-40b1-8c6c-610646426ae9/Screen Shot 2016-09-23 at 12.45.14.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5fd75c0e-f7d8-40b1-8c6c-610646426ae9%2FScreen+Shot+2016-09-23+at+12.45.14.png)

**Comment by IronRunes** [comment]
Went over this thing and got it to work without errors.
