### ISSUE TITLE
Not enough events displaying on /parties

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#75]
I suspect it's only displaying one month's worth of events - could we have all events occurring in the current month and following month?

**Comment by IronRunes** [comment]
Hello @janetgunter I checked and we are actually printing all upcoming parties.

**Comment by janetgunter** [comment]
I count 20 future events listed in the Fixometer backend, 9 in October. And I only see 3 october events listed on our website

**Comment by IronRunes** [comment]
I corrected this last night, got around to finding the gotcha. @janetgunter

**Comment by janetgunter** [comment]
Ok, now there are errors on the /parties page - the wrong groups are displaying @ironrunes

**Comment by IronRunes** [comment]
Ok, so the error here was that for some reason the "London Tour 2016" group wasn't in WP. All I did to get it to work si go to the Fixometer and save it (without editing or amending content). 
This is quite weird, I'll try to create a fake group from scratch and see what's going on. 
Now the data on the /parties page *should* be ok. @janetgunter let me know.

**Comment by janetgunter** [comment]
ah ha. this is related to the editing of groups issues in #74
