### ISSUE TITLE
Spacing of free text and link to "join us" on Group page

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#76]
https://therestartproject.org/groups/restarters-leicester/ - the text is strangely spaced/formatted and the URL is not getting grabbed for the "join us" button

**Comment by IronRunes** [comment]
@janetgunter the issue was unwanted (and unnecessary) html tags in the content. I cleaned up and everything works nicely now.

**Comment by janetgunter** [comment]
rightey-ho. how can i see that / do that myself in future?

**Comment by IronRunes** [comment]
the mechanism is as follows:
1. the websites explodes in lines looking for paragraph closing tags ( </p> ).
2. it then parses the first line to check if it's an URL
3. if it is, it strips it from the text and attaches it to the button
so basically you need to check if the link is correctly wrapped in <p></p> tags. to do so, you need to switch to code view with the last button to the right in the fixometer (the one with the "</>" icon).

**Comment by janetgunter** [comment]
ta!
