### ISSUE TITLE
Device deletion not working smoothly

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#78]
When a device is deleted, the user gets this screen, instead of returning to the list of devices at a party. 
![uploads/f8e63e37-53d4-49bf-a158-19f9e5c46b62/Screen Shot 2016-11-03 at 14.43.11 copy.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff8e63e37-53d4-49bf-a158-19f9e5c46b62%2FScreen+Shot+2016-11-03+at+14.43.11+copy.png)

**Comment by ngm** [comment]
Confirmed fixed - user now returns to list of devices at the party after device deletion.
