### ISSUE TITLE
Events still appearing the next day after they have occured

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#79]
![uploads/cd222382-305d-417b-abbb-a6ad3cb4729b/Screen Shot 2016-11-17 at 17.12.50.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcd222382-305d-417b-abbb-a6ad3cb4729b%2FScreen+Shot+2016-11-17+at+17.12.50.png)

**Comment by IronRunes** [comment]
Today this didn't happen (we had an event yesterday, and it correctly slipped away).

**Comment by ugomatic** [comment]
Yesterday, we had an event until 9.30pm but as of 7.30pm it was no longer appearing, which I believe means it disappeared right when the event started? The correct behaviour should be than an event appears on the calendar until the end of the event.

**Comment by ugomatic** [comment]
Hi @IronRunes have you been able to address my most recent comment? (I can't test it live...)

**Comment by IronRunes** [comment]
Hi @ugomatic you're right, I can amend that.

**Comment by IronRunes** [comment]
I've been working on this. The main issue seems to lie within how the server converts dates to timestamps and viceversa ( @ugomatic , a timestamp is an integer number that represents the number of second passed from 1 Jan 1970, pretty much used in computers to do date stuff). there is some misalignment that I need to investigate further and probably change a few rules both in code and on server. @ngm maybe we should look at this together? what do you think?

**Comment by ngm** [comment]
@IronRunes sure - what's the misalignment that you've seen so far?

**Comment by ngm** [comment]
@IronRunes just pinging - any progress on this?

**Comment by IronRunes** [comment]
REMINDER: I'm going set the timestamp to check across the end-time as opposed to the start-time, then check if this keeps on happening
