### ISSUE TITLE
CO2 data not matching between event page and fixometer dashboard

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/Fixometer#80]
Hi @IronRunes,
We've come across a potential problem with CO2 data. The amount of CO2 saved displayed in the event list on the dashboard (see screenshot attached)  doesn't match with the data on event-specific page, for example here: https://therestartproject.org/parties/city-hall-queens-walk-london-e1-2aa/
This is irrespective of whether we use "other" as category for any of the equipment or not
![co2-data-dashboard](https://cloud.githubusercontent.com/assets/4210589/20977495/aeec2cf0-bc9d-11e6-9c6d-2e39271e492f.png)

Please let us know what's the correct data per event, and display it consistently. Thanks a lot

**Comment by ngm** [comment]
Confirmed fixed - CO2 for City Hall, Queen’s Walk, London now matches on the event list and on the event-specific page.
