### ISSUE TITLE
Wrong CO2 and waste weight data for event

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/Fixometer#82]
This event has a huge positive environmental impact, even though it was a very small event. As a test, I've entered the exact same list of devices and repair outcomes on a test event, and got 1kg of waste / 34kg of CO2, which seems accurate. There must be a mistake, please debug it.
 ![screenshot from 2017-01-12 15-30-09](https://cloud.githubusercontent.com/assets/4210589/21991168/6bf66646-dc09-11e6-9435-5cf7a996064d.png)

**Comment by IronRunes** [comment]
Two distinct problems here. 
1. The "None of the above" weight estimate was (wrongly) being read by the system, even if the category had been changed.
2. Said weight was expressed in grams, while the system works the estimate in Kg, thus throwing that absurd number.

**Comment by ngm** [comment]
Checked and confirmed event CO2 and weight data now showing correctly for this event.  Thanks @IronRunes.

Is this a code or data fix?  i.e. will any other events have been affected, and if so, will they now also be resolved OK?  I'd like to also pull the fix into my local dev env.

**Comment by ugomatic** [comment]
Hi @IronRunes , it'd be helpful to know is this was a code or data fix, just so we can document things better. Thanks!

**Comment by IronRunes** [comment]
It was both, actually. there was some extra data in a field that made the numbers go up (namely a field that requested values in kg, but someone input "500 grams"), and some misalignment between two functions that are now flattened out. 
everything should be sorted out now.

**Comment by ngm** [comment]
Thanks @IronRunes :+1:
